maplibre/maplibre-react-native

CHANGELOG.md
plugin/src/withMapLibre.ts

Fixes [#29](https://github.com/maplibre/maplibre-react-native/issues/29)

Replace pre-install block in Expo plugin with post-install

---

CHANGELOG.md
package.json

Release of the typescript feature. As an alpha release as the api may be breaking. See https://github.com/maplibre/maplibre-react-native/pull/52#issuecomment-1713228977

update release note & version in package.json

---

CHANGELOG.md
plugin/src/withMapLibre.ts

Only set EXCLUDED_ARCHS for Release Build Settings
Enables M1/M2’s to build in debug mode simulator, without having to open Xcode and configure the project settings manually.
Closes #136

fix: plugin for debug simulator

---

.github/dependabot.yml

This updates the dependabot configuration to group updates by core, dev and example.

fix: group dependabot commits by core, dev and example

---

CHANGELOG.md
plugin/src/withMapLibre.ts

The library fails in Expo with Xcode 15 due to CocoaPods/issues/12022
This PR addresses the issue by delete the duplicate signature file in the build phase.

Fix: Duplicated Signature issue with Xcode 15 #12022

---

CHANGELOG.md
docs/MapView.md
docs/docs.json
javascript/components/MapView.tsx

Fixes some mistakes in types that I noticed during development
- I don't believe this is applicable, I can't see an `index.d.ts` file that is relevant
- Not applicable

fix: correct types in MapView

---

CHANGELOG.md
setup-jest.js

[This change was recently made in rnmapbox.][0]
This library includes an `AbortController` test mock, which doesn't work in places that expect a real one. For example, I was writing an unrelated test that tried to cancel a `fetch()` which failed because the `AbortController`'s `signal` property was invalid.
Because [`AbortController` is in all supported Node versions][1], we can safely remove this mock and rely on the real thing.
This should only affect tests.
[0]: https://github.com/rnmapbox/maps/commit/5b6489e2bffe509ff26fbdc054b693682bcdb31e
[1]: https://developer.mozilla.org/en-US/docs/Web/API/AbortController#browser_compatibility

fix: remove AbortController test mock

---

.github/workflows/on-push.yml
javascript/components/HeatmapLayer.tsx
javascript/components/ShapeSource.tsx
javascript/components/Style.tsx
javascript/components/annotations/Annotation.tsx
javascript/utils/animated/Animated.ts
package.json

Fixes https://github.com/maplibre/maplibre-react-native/issues/416
- fix typescript errors
- adds typescript check to the Github actions

fix typescript errors and add typescript:check to Github CI

---

CHANGELOG.md
javascript/components/MarkerView.tsx

Remove deprecated defaultProps for functional component

---

CHANGELOG.md
android/rctmln/src/main/java/com/maplibre/rctmln/components/location/LocationComponentManager.java

I successfully reproduced and fixed below bug
Fixes #439 
- [n/a] I updated the documentation with running `yarn generate` in the root folder
- [n/a] I updated the typings files (`index.d.ts`)
- [n/a] I added/updated a sample (`/example`)

fix: setMaxAnimationFps on null

---

CHANGELOG.md
ios/RCTMLN/MLNCustomHeaders.m

On iOS, `MLNCustomHeaders` checks the callstack for `Mapbox` to determine whether or not to intercept a request and add custom headers to it, however `Mapbox` is not present in the callstack for requests made by MapLibre, meaning that no request is ever intercepted.
This PR updates the check to look for `MapLibre` instead, which is present in the callstack, and results in requests made by MapLibre successfully being intercepted.
Apologies for some of the open tasks below, I struggled with parts of the local setup and am new to contributing to OSS. Feedback and help is very welcome and much appreciated :)
Thank you!

fix: updated Mapbox callstack check for iOS custom headers to check for MapLibre instead

---

CHANGELOG.md
javascript/components/MarkerView.tsx

`MarkerViewProps` are currently wrongly typed. There are props with defaults but the types are required. It's also a mismatch with the docs.

fix: make MarkerView props with defaults optional

---

CHANGELOG.md
android/rctmln/build.gradle
android/rctmln/src/main/java/com/maplibre/rctmln/components/mapview/RCTMLNMapView.java
android/rctmln/src/main/java/com/maplibre/rctmln/components/styles/RCTMLNStyleFactory.java
docs/FillExtrusionLayer.md
docs/RasterLayer.md
docs/SymbolLayer.md
docs/docs.json
ios/RCTMLN/RCTMLNStyle.h
ios/RCTMLN/RCTMLNStyle.m
javascript/components/annotations/Annotation.tsx
javascript/utils/MaplibreStyles.d.ts
javascript/utils/styleMap.ts
package.json
scripts/autogenHelpers/globals.js
scripts/autogenerate.js
style-spec/v8.json

Update MapLibre Android SDK to 11.5.0

feat: MapLibre Android SDK 11.5.0

---

CHANGELOG.md
javascript/utils/MaplibreStyles.d.ts
package.json
scripts/autogenHelpers/globals.js

Changes in #455, inadvertently broke style expressions. 
This PR reverts the changes to globals.js and regenerates javascript/utils/MaplibreStyles.d.ts.

fix: style expressions

---

CHANGELOG.md
javascript/components/MapView.tsx

To be able to reset `contentInset` we should accept `0` as a new value. Also the `contentInsetValue` wasn't passed as the correct native prop `contentInset`.

fix: allow resetting contentInset with 0

---

android/rctmln/build.gradle
android/rctmln/src/main/java/com/maplibre/rctmln/components/AbstractEventEmitter.java
android/rctmln/src/main/java/com/maplibre/rctmln/modules/RCTMLNLocationModule.java
android/rctmln/src/main/java/com/maplibre/rctmln/modules/RCTMLNLogging.java
android/rctmln/src/main/java/com/maplibre/rctmln/modules/RCTMLNModule.java
android/rctmln/src/main/java/com/maplibre/rctmln/modules/RCTMLNOfflineModule.java
android/rctmln/src/main/java/com/maplibre/rctmln/modules/RCTMLNSnapshotModule.java
javascript/MLNModule.ts
package.json
packages/expo-app/app.config.ts
packages/expo-app/package.json
packages/react-native-app/ios/MapLibreReactNativeExample/Info.plist
yarn.lock

This is based on https://github.com/reactwg/react-native-new-architecture/blob/main/docs/enable-libraries.md
I've collected and refined all input (thanks @rxnveer #481 and @thibaultcapelli https://github.com/maplibre/maplibre-react-native/issues/436#issuecomment-2455257208) towards the new arch support through the compatibility layer. This now compiles fine within the Expo Example app on the new architecture. Upgrade to Expo SDK 52 Preview didn't went smooth, figured to not waste more time until stable release.
It also still works on the old architecture within the React Native example app.
Fixes #436
Obsoletes #481

feat: support new arch through interop layer

---

__tests__/components/Style.test.js
__tests__/modules/offline/OfflineCreatePackOptions.test.js
__tests__/modules/offline/offlineManager.test.js
docs/docs.json
docs/offlineManager.md
src/modules/offline/offlineManager.ts

I've removed `mapbox://...` references.

chore: remove mapbox scheme urls

---

docs/Images.md
docs/MapView.md
docs/docs.json
scripts/codegen.ts

When refactoring the docs codegen I had broken the check, if the docs are up-to-date. This will fix it.

ci: fail when codegen generates something new

---

CHANGELOG.md

I forgot to cleanup the description when squashing the semantic-release commit. So all commits of that branch showed up as breaking changes. Learned for next time.

docs: cleanup changelog

---

src/MapLibreRN.ts

feat: export RegionPayload and MapLibreRNEvent types

---

android/src/main/java/org/maplibre/reactnative/utils/GeoJSONUtils.java

**Why?**
#538 
**What?**
Inside GeoJSONUtils.java, there are missing functions for converting features to GeoJSON for MultiPoint, MultiLineString and MultiPolygon. This causes `<VectorSource/>`'s `onPress` to return `event.features` as `null`
**What?**
Add missing functions inside GeoJSONUtils.java for converting features to GeoJSON for MultiPoint, MultiLineString and MultiPolygon

fix: `VectorSource` `onPress` returning null geometry on Android

---

ios/MLRN/MLRNStyle.m
scripts/templates/MLRNStyle.m.ejs

[Another left-over](https://github.com/rnmapbox/maps/commit/e44371675ef98dd50c96f10eded12d3b9fa52a2f#diff-2475e07fe9507927fa8d5231946cdf0604d7c2e920fe2afaa3e96b9862e2addbR126-R128) from a long removed component.

chore: remove obsolete `__MAPBOX_STYLESHEET__` check

---

packages/examples/src/assets/styles/maplibre-demo-tiles-blue.json
packages/examples/src/assets/styles/maplibre-demo-tiles-white.json

These two example styles had some minor issues, like the empty `sprite` and `glyph` urls which threw a warning when loading.

chore: cleanup example styles

---

docs/components/Camera.md
docs/components/MapView.md
docs/docs.json
docs/guides/Logger.md
docs/modules/OfflineManager.md
src/components/Camera.tsx
src/components/MapView.tsx
src/modules/offline/OfflineManager.ts

Use lower case `string`, `boolean` and `number` types as [recommended by TypeScript](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#the-primitives-string-number-and-boolean).

docs: use lower case primitives

---

android/src/main/java/org/maplibre/reactnative/utils/GeoJSONUtils.java

- Added `fromGeometryCollection`, as `GeometryCollection` is a valid `geometry` too
- Improved some `null` checks
Noticed these during reviewing #555

fix: added GeometryCollection to GeoJSONUtils

---

.github/workflows/release.yml

Docusaurus seems to have some package aliased, which in conjunction with yarn workspaces breaks `npm audit signatures`, see this job: https://github.com/maplibre/maplibre-react-native/actions/runs/12715049694/job/35451931426.
By deleting the `docs/node_modules` before `npm audit signatures` it's fixed. You can test locally, with the directory present `npm audit signatures` will fail.

ci: fix audit signatures

---

.github/workflows/review-ios.yml

iOS startup is a bit flaky currently: https://github.com/maplibre/maplibre-react-native/actions/runs/12741854668/job/35509351876#step:5:13
Trying to fix it with their recommendation from the docs: https://maestro.mobile.dev/advanced/configuring-maestro-driver-timeout

ci: increase MAESTRO_DRIVER_STARTUP_TIMEOUT

---

.github/workflows/docs.yml

`$default-branch` is only used for actions templates, doesn't work in a workflow.

ci: set branch properly for docs workflow

---

docs/docusaurus.config.ts

The credentials are public and can be committed
- https://docusaurus.io/docs/search#connecting-algolia
- https://support.algolia.com/hc/en-us/articles/18966776061329-Can-the-search-API-key-be-public
To test, just check out this branch and run `yarn docs start` and search should already be working.

docs: add search

---

android/build.gradle
android/gradle.properties
docs/content/setup/library-customizations.md
src/plugin/MapLibrePluginProps.ts

Fixes #590 
This allows configuration OpenGL ES or Vulkan variant of Android SDK at build time.

feat: allow configuration of Android SDK variant

---

src/__tests__/plugin/android/mergeGradleProperties.test.ts
src/plugin/android.ts

Previously the Expo plugin would have not remove a property, when removing it from `app.json` or `app.config.{js,ts}`. It only overwrote duplicates. This should not be the case, as it would leave artifacts within the generated `gradle.properties`, making the plugins output for Android non-deterministic. For example the broken behavior previously:
1. Set `locationEngine: "google"` in `app.config.ts`
2. Run `expo prebuild`
This will add `org.maplibre.reactnative.locationEngine=google` to `gradle.properties`
3. Remove `locationEngine: "google"` in `app.config.ts` again
4. Run `expo prebuild`
`org.maplibre.reactnative.locationEngine=google` will still be in `gradle.properties`
Now all old properties from MLRN are removed and only the current plugin props are applied.

fix: plugin remove obsolete `gradle.properties`

---

.clang-format
.git-blame-ignore-revs
CONTRIBUTING.md

I've added https://github.com/maplibre/maplibre-native/blob/main/.clang-format for formatting the ios files.
Merge after #690, which I will also add to the `.git-blame-ignore-revs` in this PR.

chore: add .clang-format

---

ios/MLRN/CameraUpdateItem.m

Fixes #633
For the bounds it's enough to check, if `>= -90 latitude <= 90`. with these changes the following examples works the same on iOS as it already did on Android:
```tsx
import {
Camera,
type CameraRef,
CircleLayer,
LineLayer,
MapView,
ShapeSource,
} from "@maplibre/maplibre-react-native";
import { featureCollection, point } from "@turf/helpers";
import { useRef } from "react";
import { Button } from "react-native";
const AN = point([-149.863129, 61.217381]);
const AN_POSITIVE_BUT_INVALID = point([210.863129, 61.217381]);
const TO = point([139.839478, 35.652832]);
export function BugReport() {
const cameraRef = useRef<CameraRef>(null);
return (
<>
<Button
onPress={() => {
cameraRef.current?.fitBounds(
AN.geometry.coordinates,
TO.geometry.coordinates,
[100, 100, 100, 100],
0,
);
}} …
```

fix: fitBounds on iOS across 180th meridian

---

src/plugin/ios.ts
src/plugin/withMapLibre.ts

This fix only applies to consumers using Expo continuous native code generation. This change also only applies to the iOS project code generated.
Before the PR, the pbxproj file includes this:
After the PR, the pbxproj file does NOT contain the line to exclude arm64 symbols:

fix: remove expo plugin withExcludedSimulatorArchitectures
